export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT';
// export const GET_DEPARTMENT = 'GET_DEPARTMENT';
// export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
// export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';
export const SUCCESS = "SUCCESS";
export const FETCHING = "FETCHING";
export const FAILURE = "FAILURE";